// src/lib/components/Arrival.svelte
<!-- linkhub-beta/src/lib/components/Arrival.svelte
     Copyright (c) 2026 Clove Nytrix Doughmination Twilight
     Licensed under the DASL-1.0 Licence.
     See LICENCE.md in the project root for full licence information.
-->

<script lang="ts">
	import { Link, MapPin, MessageCircle } from '@lucide/svelte';

	import { arrival } from '$lib/app/arrival.svelte';
	import { greetingFor, primarySubdomain, rootDomain } from '$lib/data/subdomains';
	import { siteForHost } from '$lib/data/sites';

	const currentSubdomain = $derived(arrival.subdomain ?? primarySubdomain);
	const referrerSite = $derived(arrival.referrerHost ? siteForHost(arrival.referrerHost) : null);
</script>

<div class="arrival">
	<p class="arrivalLine">
		<MapPin class="icon" aria-hidden="true" />

		<span>
			you arrived on
			<span class="arrivalHost">{currentSubdomain}</span><span class="arrivalRoot"
				>.{rootDomain}</span
			>
		</span>
	</p>

	{#if arrival.referrerHost}
		<p class="arrivalLine">
			<Link class="icon" aria-hidden="true" />

			<span>
				came over from
				<span class="arrivalHost">
					{referrerSite?.title ?? arrival.referrerHost}
				</span>
			</span>
		</p>
	{/if}

	<p class="arrivalLine">
		<MessageCircle class="icon" aria-hidden="true" />

		<span>{greetingFor(currentSubdomain)}</span>
	</p>
</div>

// src/app/Arrival.tsx
/* info/src/app/Arrival.tsx
 * Copyright (c) 2026 Clove Nytrix Doughmination Twilight
 * Licensed under the DASL-1.0 Licence.
 * See LICENCE.md in the project root for full licence information.
 */

"use client";

import {
  Link,
  MapPin,
  MessageText,
} from "pixelarticons/react";

import {
  arrival,
  arrivalLine,
  arrivalHost,
  arrivalRoot,
  icon,
} from "@styles/home.css";
import {
  greetingFor,
  primarySubdomain,
  rootDomain,
} from "@data/subdomains";
import { siteForHost } from "@data/sites";
import {
  useCurrentSubdomain,
  useReferrerHost,
} from "@app/useArrival";

export default function Arrival() {
  const currentSubdomain = useCurrentSubdomain() ?? primarySubdomain;
  const referrerHost = useReferrerHost();
  const referrerSite = referrerHost ? siteForHost(referrerHost) : null;

  return (
    <div className={arrival}>
      <p className={arrivalLine}>
        <MapPin
          className={icon}
          aria-hidden
        />
        <span>
          you arrived on{" "}
          <span className={arrivalHost}>{currentSubdomain}</span>
          <span className={arrivalRoot}>.{rootDomain}</span>
        </span>
      </p>

      {referrerHost && (
        <p className={arrivalLine}>
          <Link
            className={icon}
            aria-hidden
          />
          <span>
            came over from{" "}
            <span className={arrivalHost}>
              {referrerSite?.title ?? referrerHost}
            </span>
          </span>
        </p>
      )}

      <p className={arrivalLine}>
        <MessageText
          className={icon}
          aria-hidden
        />
        <span>{greetingFor(currentSubdomain)}</span>
      </p>
    </div>
  );
}
